name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Thisizzellie
          outputs: dist/snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "Update snake"
