name: Generate Commit Dinosaur Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Dinosaur SVG
        run: |
          echo "Using dinosaur.svg from .github/workflows/"

      - name: Push Dinosaur SVG to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/dinosaur.svg
          git commit -m "Generated Din
