name: Generate Commit Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate commit animation
        uses: Platane/snk@v3
        with:
          github_user_name: "Thisiszellie" # Replace with your username

      - name: Push the generated SVG to the repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generated commit animation 🦖"
          git push

